name: flutter_piano
description: A Crossplatform Midi Piano built with Flutter.
author: Rody Davis Jr <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/flutter_piano
version: 1.5.1+400
publish_to: none

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_midi:
    path: ../third_party/flutter_midi/flutter_midi
  app_review: ^2.0.1
  url_launcher: ^6.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^8.4.0
  tonic: ^0.2.3
  vibrate: ^0.0.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  screenshots: ^0.1.7
  test: ^1.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/Piano.sf2
